// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtAh8V2TXe_k963z9MhczTS6i7g8KVvE',
    appId: '1:653965954163:web:b8c5a33c797900139d2e06',
    messagingSenderId: '653965954163',
    projectId: 'giggl-chat-app',
    authDomain: 'giggl-chat-app.firebaseapp.com',
    storageBucket: 'giggl-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1E9hKfcGLfEOgWflQK5M8DIf-M7L11rw',
    appId: '1:653965954163:android:3d5b271e0d5762199d2e06',
    messagingSenderId: '653965954163',
    projectId: 'giggl-chat-app',
    storageBucket: 'giggl-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbna5TtKaXAgdyBApevATJ4adBc6W2tw',
    appId: '1:653965954163:ios:a092867a2d2c2ce69d2e06',
    messagingSenderId: '653965954163',
    projectId: 'giggl-chat-app',
    storageBucket: 'giggl-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbna5TtKaXAgdyBApevATJ4adBc6W2tw',
    appId: '1:653965954163:ios:a092867a2d2c2ce69d2e06',
    messagingSenderId: '653965954163',
    projectId: 'giggl-chat-app',
    storageBucket: 'giggl-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatMessengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGtAh8V2TXe_k963z9MhczTS6i7g8KVvE',
    appId: '1:653965954163:web:55a31c182ade34159d2e06',
    messagingSenderId: '653965954163',
    projectId: 'giggl-chat-app',
    authDomain: 'giggl-chat-app.firebaseapp.com',
    storageBucket: 'giggl-chat-app.firebasestorage.app',
  );
}
